name: Indeed Worker

on:
  workflow_dispatch:
  schedule:
    - cron: "17 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - run: node indeed.js
        env:
          WEBAPP_URL: ${{ secrets.WEBAPP_URL }}
